


export let GETHOTELS_REQUEST="GETHOTELS_REQUEST";

export let GETHOTELS_SUCCESS="GETHOTELS_SUCCESS";

export let GETHOTELS_FAILURE="GETHOTELS_FAILURE";


// for payment //

export let TOTALPRICE="TOTALPRICE "
export let TOTAL_DAYS="TOTAL_DAYS";